Release/20230225
f-lab-edu/messenger-tempo pull request #23
Opened 2023-02-25 07:37 UTC by tempo001

2023-02-25 16:09 UTC, f-lab-moony requested changes
고생 많으셨습니다~
전체적으로 큰 흐름보단 작은 디테일에 힘이 들어간 느낌이에요!
너무 많은 예외상황을 고려하려고 하지 않으시는게 좋을 것 같습니다 😄 

그리고 마이바티스 적용 못한 이유가 약간 이해가 안되는데요, Member가 Entity 역할을 수행하면 Member는 불변해야 하는 대상이 맞을까요?

불변객체가 안정성이 뛰어난 건 사실이지만 불변만이 정답은 아닙니다.

이런 주제로 다음 멘토링 시간에 얘기 나눠보면 좋을 것 같아요!
그럼 계속해서 화이팅 해주세요 :)

2023-02-25 16:09 UTC, f-lab-moony commented on src/main/java/com/messenger/service/MemberService.java
> +            Optional<Member> findMemberSession = findById(sessionUserId);
이 부분은 약간 이해가 안되네요? 세션이 유효하면 로그인 중으로 판단하는데 유저가 있는지 다시 확인하는게 맞을까요 ?

2023-02-26 14:38 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcTemplateMemberRepository.java
> +            update = jdbcTemplate.update(sql, args);
영향을 받은 행의 개수를 의미합니다

2023-02-26 14:51 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +                Member member = new Member(memberId, memberPw, displayName, statusMessage);
클래스의 모든 필드값을 가진 생성자를 만들때, 
builder 보다는 모든 필드를 매개변수로 갖는 생성자 쪽이 더 깔끔해보이고, 
필드값을 하나라도 누락하는 경우 컴파일 에러로 알려주기 때문에
모든 필드값을 가진 생성자를 만들때는 builder 대신 생성자를 사용했습니다

2023-02-26 14:57 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +//@Repository
`JdbcTemplateMemberRepository`를 Repository로 등록하여 사용하고 있는데
같은 `MemberRepository` 타입인 `JdbcMemberRepository`도 Repository로 등록하면 
`@Autowired`를 할 수 없어서 주석처리했습니다

2023-02-26 14:59 UTC, tempo001 commented on src/main/java/com/messenger/domain/Member.java
> +@AllArgsConstructor(access = AccessLevel.PUBLIC)
알려주신 링크로 다시 한 번 살펴보겠습니다. 링크 감사합니다!

2023-02-26 15:04 UTC, tempo001 commented on src/main/java/com/messenger/exception/MyException.java
> +    public final Object object;
REST API 컨트롤러에서 try catch 구문으로 예외를 잡았을때 
errorCode로 HTTP status code를 결정하고, object로 반환값을 결정합니다.

지금까지는 MyException의 object가 모두 null 이지만, 혹시 나중에 null이 아닌 객체를 반환할 일이 생길 수 있을까봐 만들어두었습니다.

2023-02-26 15:06 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcTemplateMemberRepository.java
> +            log.warn(e.getMessage());
예외를 뱉어내게 만들고, save()의 리턴 타입을 Member로 바꾸겠습니다

2023-02-26 15:08 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcTemplateMemberRepository.java
> +        return update == 1;
실패할 경우 예외를 뱉어내게 만들고, 
성공할 경우 Member를 리턴하도록 바꾸겠습니다

2023-02-26 15:44 UTC, tempo001 commented on src/main/java/com/messenger/service/MemberService.java
> +        if (!ret) {
memberRepository.updateMember가 예외를 뱉어내도록 수정하고, 이 부분은 삭제하겠습니다

2023-03-09 02:54 UTC, f-lab-moony approved these changes
피드백 반영을 늦게 봤네요! PR이 두개가 있어 뭐지 싶다가 확인했어요..!
피드백 반영 잘 해주셔서 바로 머지 하겠습니다!

2023-03-09 02:54 UTC, merged