[issue-3] 회원가입 api 작성
f-lab-edu/messenger-tempo pull request #7
Opened 2023-02-13 10:37 UTC by tempo001

2023-02-13 12:54 UTC, f-lab-moony requested changes
첫번째 PR 잘 봤습니다!
리뷰 체인지로 돌려보내기를 해볼텐데요, 코멘트 확인하시고 피드백 반영 하신 뒤에 다시 푸시하시면 변경 내역 저한테 보일거에요!

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/domain/Member.java
> +    public void setPassword(String password) {
prefix로 `set_`은 지양하는게 좋아요. 기본적으로 만들어주는 getter/setter와 구분이 안되어서 의도를 파악하기가 어려워요!

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/domain/Member.java
> +    public Member(String id, String password, String name) {
생성자가 두 개 있어야 하는 이유를 잘 모르겠어요! 두개로 나누신 이유가 뭘까요 ?

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/domain/Member.java
> +    public Member(String id, String password) {
Lombok의 `@Builder`도 사용해보시면 좋을 것 같아요 ~

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/domain/Member.java
> +public class Member {
엔티티정의를 잘 해 주셨네요 :) 약간 JPA 느낌이 나요!
근데 저희 스키마가 어떻게 생긴지 안보여서 조금 아쉽네요
DB 스키마 형상관리 라이브러리로 [flyway](https://sabarada.tistory.com/193)라는게 있는데, 한 번 찾아보시고 적용하면 좋을 것 같아요!

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +        ResultSet rs = null;
rs는 아예 안쓰이는 것 같네요 ?

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +            if (ret != 1) {
return값까지 세심하게 체크하는 부분 좋네요 :)
하지만 굳이 필요할까 싶은데 어떻게 생각하시나요 ?

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +    public Optional<Member> findById(String id) {
Optional 사용 좋습니다 :)

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +            if (rs.next()) {
보통 findById는 getOne같은 의미로, id에 대해 하나의 값만 존재한다는 전제 하에 사용해서 두 개 이상의 응답이 나올 경우 예외가 발생하는 부분이 있어요!

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +            conn.setAutoCommit(false);  // 트랜잭션 시작
autoCommit = false 는 getConnection을 할때 디폴트로 넣어줘도 되지 않을까요 ?

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +            if (ret != 1) {  // 이전과 동일한 경우도 예외 발생하게 처리
이전과 동일한 경우는 왜 예외가 발생해야 할까요 ?

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +    public boolean updateDisplayName(String id, String name) {
변경 가능한 필드가 많아질수록 메서드가 엄청나게 늘어날 것 같은데, 다른 방법은 없을까요 ?

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/repository/MemberRepository.java
> +public interface MemberRepository {
인터페이스 정의 좋네요 👍

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/service/MemberService.java
> +        boolean result = validateDuplicateMember(member);
Duplicate는 DB의 제약조건으로 처리할 수 있지 않을까요 ?

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/web/MemberController.java
> +    public MemberController(MemberRepository memberRepository, MemberService memberService) {
repository는 안쓰이는 것 같아요!

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/web/MemberController.java
> +    @Autowired
아시겠지만, `@Autowired`는 굳이 안붙여도 됩니다!

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/web/MemberController.java
> +    @PostMapping(value = "/api/member/signup", consumes = "application/x-www-form-urlencoded")
consumes는 혹시 왜 urlencoded로 지정이 된걸까요 ?

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/web/MemberController.java
> +    @PostMapping(value = "/api/member/signup", consumes = "application/x-www-form-urlencoded")
아, 그리고 path는 보통 도메인 클래스의 복수형으로 잡고 단순 CRUD에 대해서는 메서드 타입으로 분기하는 편이에요!
+ 버전도 명시해두면 좋습니다!

위 엔드포인트들을 예로 들면

전체회원목록 : GET /api/v1/members
회원 등록 : POST /api/v1/members

회원 단건 조회가 생긴다면 GET /api/v1/members/{memberId}

이런식으로요!

2023-02-13 12:54 UTC, f-lab-moony commented on src/main/java/com/messenger/domain/Member.java
> +        if (!name.equals("")) {
의견이 분분한 내용이긴 한데, 빈값이나 null 처리 등의 간단한 유효성 검사는 [Spring Validation](https://mangkyu.tistory.com/174)을 이용해서 앞단에서 처리 하는것도 좋다고 생각합니다!

2023-02-13 12:54 UTC, f-lab-moony commented on src/test/java/com/messenger/repository/MemberServiceIntegrationTest.java
> +public class MemberServiceIntegrationTest {
테스트는 정상적으로 작동하지 않는 것 같아요!

2023-02-13 13:28 UTC, tempo001 commented on src/main/java/com/messenger/domain/Member.java
> +public class Member {
DB 스키마는 [이 파일](https://github.com/f-lab-edu/messenger-tempo/blob/main/sql/DDL.sql)에 있습니다.
flyway는 한번 알아보겠습니다.

2023-02-13 13:35 UTC, tempo001 commented on src/main/java/com/messenger/domain/Member.java
> +    public Member(String id, String password, String name) {
name이 정의되지 않았을때와 정의되었을때 모두 객체를 만들기 위해서 2개로 만들었습니다.

2023-02-13 15:10 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +            if (ret != 1) {
변경이 되었는지 여부를 확인하려고 넣었는데, 
여기에서는 변경 여부를 확인하지 않게 `int ret` return 변수를 삭제하고 
컨트롤러에서 변경 전후의 객체를 비교하는 걸로 바꾸었습니다 (#8)

2023-02-13 15:22 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +        ResultSet rs = null;
안 쓰이는 변수 삭제했습니다

2023-02-13 15:30 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +            if (ret != 1) {  // 이전과 동일한 경우도 예외 발생하게 처리
[여기](https://github.com/f-lab-edu/messenger-tempo/pull/7#discussion_r1104604362)와 같은 이유로 수정했습니다

2023-02-13 15:32 UTC, tempo001 commented on src/main/java/com/messenger/web/MemberController.java
> +    public MemberController(MemberRepository memberRepository, MemberService memberService) {
삭제했습니다

2023-02-13 15:39 UTC, tempo001 commented on src/main/java/com/messenger/web/MemberController.java
> +    @PostMapping(value = "/api/member/signup", consumes = "application/x-www-form-urlencoded")
웹 브라우저에서 POST 요청은 대부분 form으로 전송하는 것 같아서 
form으로 전송된 POST 요청만 받기 위해서 `application/x-www-form-urlencoded`로 설정했습니다

2023-02-13 16:21 UTC, tempo001 commented on src/main/java/com/messenger/web/MemberController.java
> +    @PostMapping(value = "/api/member/signup", consumes = "application/x-www-form-urlencoded")
엔드포인트 수정했습니다

2023-02-14 09:04 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +    public boolean updateDisplayName(String id, String name) {
파라미터로 객체를 넘겨주면 될 것 같습니다

2023-02-14 09:27 UTC, tempo001 commented on src/main/java/com/messenger/domain/Member.java
> +    public Member(String id, String password) {
@Builder 한번 살펴봤습니다.
개인적으로 여기서는 필드가 많지 않아서 @Builder를 안 쓰는게 더 나을 것 같습니다

2023-02-14 09:47 UTC, tempo001 commented on src/main/java/com/messenger/repository/JdbcMemberRepository.java
> +            conn.setAutoCommit(false);  // 트랜잭션 시작
다시 생객해봤는데 쿼리가 하나밖에 없어서 
오토 커밋 모드를 false로 지정할 필요가 없는 것 같네요

2023-02-14 10:01 UTC, f-lab-moony commented on src/main/java/com/messenger/domain/Member.java
> +    public Member(String id, String password) {
선택은 존중합니다! 하지만 `@Builder`는 파라미터 갯수때문에 쓰는 건 아니라서 다시 한번 살펴보시는 게 좋을 것 같아요 :)
그리고 어노테이션을 달때는 ` 으로 감싸주세요! 안감싸고 쓰면 사람이 태그가 됩니다..!

2023-02-14 12:13 UTC, merged